//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beloArte.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_CLIENTE
    {
        public int CODCLIENTE { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string SEXO { get; set; }
        public string CPF { get; set; }
        public string TELEFONE { get; set; }
        public Nullable<System.DateTime> DTNASCIMENTO { get; set; }
    }
}
