//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beloArte.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_ENDERECO
    {
        public int CODENDERECO { get; set; }
        public string ENDERECO { get; set; }
        public string NUMERO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string BAIRRO { get; set; }
        public string COMPLEMENTO { get; set; }
    }
}
