//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beloArte.Domain
{
    public partial class BA_PRODUTO
    {
        public int CODPRODUTO { get; set; }
        public string IMG { get; set; }
        public string TITULO { get; set; }
        public string DESCRICAO { get; set; }
        public double VALOR { get; set; }
        public string CATEGORIA { get; set; }
    }
}
