//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beloArte.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloEntidades : DbContext
    {
        public ModeloEntidades()
            : base("name=ModeloEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BA_CLIENTE> BA_CLIENTE { get; set; }
        public virtual DbSet<BA_ENDERECO> BA_ENDERECO { get; set; }
        public virtual DbSet<BA_USUARIO> BA_USUARIO { get; set; }
    }
}
